### ISSUE TITLE
inProdTableBlock should be {zero_block, one_block}?

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-agmpc#14]
This is related to the `inProd` function in this repo.
https://github.com/emp-toolkit/emp-agmpc/blob/master/emp-agmpc/helper.h#L15

It uses the following selection pad:
```
const static block inProdTableBlock[] = {zero_block, makeBlock(0xFFFFFFFFULL, 0xFFFFFFFFULL)};
```

However, the one pad here is not fully one. In fact, a fully one pad should be:
```
const block all_one_block = makeBlock(0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF);
```

Note that `emp-tool`'s `'block.h` offered `const block select_mask[2] = {zero_block, all_one_block};`, which could be a drop-in replacement here.

**Comment by wangxiao1254** [comment]
fixed!
