### ISSUE TITLE
A candidate implementation for flexible input/output for BristolFormat

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-agmpc#16]
Ryan Deng (@ryandeng1) and I implemented a fork of EMP-AGMPC that supports flexible input/output, which suffices for reactive computation.

Fork: https://github.com/n-for-1-auth/emp-agmpc-flex-in-out

## Features

Basically, inputs and outputs are flexible in the following ways.

Each bit of the input can be in one of four modes:
- **Secret-shared, un-authenticated.** (denoted by -2) Each party provides a bit, and the actual input to the GC is the XOR of all the parties' bit. This is useful for providing a random tape.
- **Secret-shared, authenticated.** (denoted by -1) Parties provide an authenticated bit (bit, mac, key), likely from a previous execution under the same delta key.
- **Public** (denoted by 0). All party enforces this input bit to be something agreed publicly.
- **Private** (denoted by party ID). One party provides this bit.

Each bit of the output can be in one of three modes:
- **Secret-shared, authenticated.** (denoted by -1) Parties obtain an authenticated bit representing the output. This authenticated bit can then be fed into another AGMPC execution, if under the same delta key.
- **Public** (denoted by 0). All party sees this output.
- **Private** (denoted by party ID). One party sees this bit.

## API 

The input array is replaced by `FlexIn<nP>`. Parties first agree on the mode (here, "party") of each bit. 

```
FlexIn<nP> in(cf.n1 + cf.n2, party);
for(int i = 0; i < 64; i++) {
	in.assign_party(i, ALICE);
}
for(int i = 64; i < cf.n1; i++) {
	in.assign_party(i, BOB);
}
```

And the party can feed a bit or an authenticated bit into it.
```
for(int i = 0; i < cf.n1; i++){
	in.assign_plaintext_bit(i, i % 2 == 0);
}
for(int i = 0; i < cf.n2; i++) {
	AuthBitShare<nP> mabit = out.get_authenticated_bitshare(i);
	in.assign_authenticated_bitshare(cf.n1 + i, &mabit);
}
```

The output array is replaced by `FlexOut<nP>`, which works in a similar fashion.

```
FlexOut<nP> out(cf.n3, party);
for(int i = 0; i < 32; i++) {
	out.assign_party(i, ALICE);
}
for(int i = 32; i < 64; i++) {
	out.assign_party(i, BOB);
}
for(int i = 64; i < cf.n3; i++) {
	out.assign_party(i, 0);
}
```

One can get an authenticated bit like this, after the online phase.
```
out.get_authenticated_bitshare(i);
```

Or, if the party is allowed to see the plaintext value, it can do:
```
if(party == ALICE) {
	for (int i = 0; i < 32; i++) {
		cout << out.get_plaintext_bit(i) << " ";
	}
	for (int i = 32; i < 64; i++) {
		cout << "x" << " ";
	}
	for (int i = 64; i < cf.n3; i++) {
		cout << out.get_plaintext_bit(i) << " ";
	}
}
```

## Test 

The code has been tested for 2 parties over the AES circuit. This test script tries all the functionalities and compares them with the original input/output framework.

https://github.com/n-for-1-auth/emp-agmpc-flex-in-out/blob/master/test/test_in_out.cpp 

## Potential improvement

There are two potential improvements to the code.

- Due to laziness, the current implementation sends out a lot of dummy data (and they are all zeroes) during the input/output. Careful implementation of the broadcast will get rid of such communication.  
- Due to laziness, the MAC checking is not batched. That is to say, one party actually sends out the MAC of an authenticated bit for MAC testing. We know this could be reduced by using a hash over the MAC. 

We feel this should be fine since input/output is often small, compared with the circuit size. But this may not always be the case. 

## Roadmap to merging

Though the commit is small, there are two obstacles.

- The memory corruption issue of #10.
- In this implementation, passing authenticated bits between different `CMPC` objects requires the same delta key. Our fork hardcodes this delta key, which is insecure. We might need a way to generate and use the same delta key across a number of instances that require such reactive computation (and not do so when not needed). Ferret's COT has a setup phase that seems relevant.

So, the code is currently left as a fork.

## Potential next steps

Note that EMP-AGMPC currently only supports BristolFormat, but, especially given this framework, BristolFashion should work as well. A possible direction is to allow easy conversion from BristolFormat to BristolFashion or merge their API.

## Credits

This implementation is made when working on https://eprint.iacr.org/2021/342. 

We also leveraged some code snippets of [Senate](https://eprint.iacr.org/2020/1350) by @podcastinator and @sukritkalra.

**Comment by wangxiao1254** [comment]
It looks awesome! It will take some time for me to review but I will try to finish it ASAP.

**Comment by wangxiao1254** [comment]
I merge in progress at `n-for-1-auth-master `! The rest part of the job requires me to take a look at the new code before deciding the issue with Delta.
