### ISSUE TITLE
If one wants semi-honest security, should this person just mute a few checks?

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-agmpc#2]
It is known that AG-MPC has similar performance with the prior work in semi-honest MPC; however, AG-MPC achieves malicious security.

One who wants the fastest semi-honest MPC may want to start from AG-MPC and turn AG-MPC into semi-honest. 

The shortcut is thus to find invocations to SHA256 that are unnecessary for the semi-honest setting. 

My observation is that:

- No need to cut calls to H outside \Pi_{Pre}, we cannot simply delete any H, but at most think to reduce the hash output size of H from 64 bytes to 48 bytes (and then removing MAC). However, H is a SHA256 hash function supported by CPU instructions, so shrinking the output does not save anything.
- Cut the checking in \Pi_{aShare}, basically, set \rho to 0. This saves the invocation to commitment schemes. That is to say, in this implementation, cut check2 in abitmp.h.
-  Cut the triple checking in \Pi_{LaAND}. This is some code in fpremp.h, from https://github.com/emp-toolkit/emp-agmpc/blob/master/emp-agmpc/fpremp.h#L134 to 227, I guess. This again cuts a few calls to H and commitments.
- There is a check in \Pi_{aBit}, yet this seems not involving any invocation to H. This part of the code should be check1 in abitmp.h. Again, we can set \rho to 0.

Any thoughts or advice?

**Comment by wangxiao1254** [comment]
On Tue, Mar 5, 2019 at 3:57 AM Weikeng Chen <notifications@github.com>
wrote:

> It is known that AG-MPC has similar performance with the prior work in
> semi-honest MPC; however, AG-MPC achieves malicious security.
>
> One who wants the fastest semi-honest MPC may want to start from AG-MPC
> and turn AG-MPC into semi-honest.
>
> The shortcut is thus to find invocations to SHA256 that is unnecessary for
> the semi-honest setting.
>
> My observation is that:
>
>    - No need to cut calls to H outside \Pi_{Pre}, we cannot simply delete
>    any H, but at most think to reduce the hash output size of H from 64 bytes
>    to 48 bytes (and then removing MAC). However, H is a SHA256 hash function
>    supported by CPU instructions, so shrinking the output does not save
>    anything.
>    - Cut the \rho checking in \Pi_{aShare}, basically, set \rho to 0.
>    This saves the invocation to commitment schemes. Or, in this
>    implementation, cut check2 in abitmp.h.
>    - Cut the triple checking in \Pi_{LaAND}. This is some code in
>    fpremp.h, from
>    https://github.com/emp-toolkit/emp-agmpc/blob/master/emp-agmpc/fpremp.h#L134
>    to 227, I guess. This again cuts a few calls to H and commitments.
>    - There is a check in \Pi_{aBit}, yet this seems not involving any
>    invocation to H. This part of the code should be check1 in abitmp.h. Again,
>    we can set \rho to 0.
>
> Any thoughts or advice?
>
In general, no need to think about hash calls since communication is more
significant. Here is one roadmap that should work:
1. replace all malicious protocols to semi-honest protocol: malicious OT ->
semi-honest OT
2. make rho = 0: no bucketing, no (kappa+rho)-bit OT but only kappa-bit OT
This is huge due to the processing cost there
3. eliminate all MACs.

After these steps, it should be a version that I would guess around 7-10
times faster. Other changes would require benchmarking the implementation
again.

Xiao

**Comment by weikengchen** [comment]
Thanks for the information.

**Comment by weikengchen** [comment]
Done 1/2. It seems that to eliminate all MACs, we will:

(1) Eliminate all MAC and MAC keys after the function-independent protocol, which can shrink the circuit size, and cut the calls to PRP.
(2) F_{aShare} no longer generates MAC. Rather, each party chooses its own share of the x locally. This eliminates the communication for authenticated bits.
(3) \Pi_{HaAND} will need to use a different approach to avoid MAC and MAC keys. Rather, it will become a pairwise general OT extension.
(4) No need to turn multiple leaky AND triplets into one, that is to say, set the bucket size to 1.

**Comment by weikengchen** [comment]
The circuit evaluation logic omits r^i_{\gamma,\ell}; rather, it learns the r^i using a MAC check using M_1 and K_1. If one wants to remove MAC, he/she needs to find a way to recover r^i. 

My plan will be shrinking the label to 127 bits and stealing the last bit of the label for r^i when in the garbled table.

**Comment by weikengchen** [comment]
Closed. It seems not that easy to eliminate all MACs since their relationship with the corresponding keys is used to adjust the output wire of each AND gate into z_w \oplus \lambda_w.

**Comment by wangxiao1254** [comment]
Or may be you can reduce it to 1 bit/byte.

**Comment by weikengchen** [comment]
However, if I read the paper correctly, we need to use the fact that:
 - K[x]\oplus M[x] = \Delta_A, if x = 1 and A holds K.
 - K[x]\oplus M[x] = 0^\ell, if x = 0 and A holds K.

This is crucial for the correctness. In the garbled circuit, by XORing the last column with the MACes of other parties' "r" under this party's keys, we can bring the output wire of this AND gate in all parties' circuits to z_w\oplus r_w, where r_w is the XOR of all parties' XOR of this AND gate's r, not just one party's.

**Comment by wangxiao1254** [comment]
I was talking about the MAC in the garbled circuit, not IT-MACs. Note that
IT-MACs are 128-bit long, but MAC of the GC is only 40 bit long. See the
bottom of Figure 2, inside of what's encrypted, there are three terms. The
first term is a bit, the second term is a MAC, the last term is a share of
GC (but also constructed using IT-MACs).

**Comment by weikengchen** [comment]
I reread the paper and sort of have a different opinion (though I know you wrote this paper).

If you have time, feel free to correct... I do not plan to eliminate the IT-MAC so this is not urgent at all. 

So in Figure 2 of Page 6 in [https://acmccs.github.io/papers/p39-wangA.pdf](https://acmccs.github.io/papers/p39-wangA.pdf), in Step 4(d) of function-dependent phase,
 - The second term is a list of MACs. In the current implementation, each of the MAC is actually a 128-bit block. See the Hash function in `mpc.h` for more detail.
https://github.com/emp-toolkit/emp-agmpc/blob/c93925fa11ee49aa1db22864eccebd9381cf7399/emp-agmpc/mpc.h#L441
 
 - The first player needs to use these MACs (from other parties' garbled table) to XOR with the last term (a share of GC), in order to compute L^i_{\gamma,z_\gamma\oplus\lambda_gamma}. This is step 7 in circuit evaluation. Thus, these MACs on the second term must be 128-bit IT-MACs under the same \Delta_i used for labels.

The second point is because the last term in each row of the garbled table is:
     `L^i_{\gamma,0} \oplus (XORSum of Ks of others' r_{\gamma, 0}) \oplus r^i_{\gamma,0}\Delta_i`

If we XOR this term with the MACs in other parties' chosen row's second term, we have:
     `L^i_{\gamma,0} \oplus (XORSum of r^i_{\gamma,0})\Delta_i`

Since `XORSum of r^i_{\gamma,0}` equals `z_\gamma \oplus \lambda_gamma`, the above term is:
     `L^i_{\gamma,z_\gamma \oplus \lambda_gamma}`.

Thus, I feel MAC here needs to be like the IT-MAC.
