### ISSUE TITLE
Doesn't build on clean Ubuntu 18.04

### ISSUE THREAD

**Issue by DerJesko** [emp-toolkit/emp-agmpc#20]
`cmake -DENABLE_FLOAT=False .` as seen in the install script does not work on a clean Ubuntu 18.04 install.
```
CMake Error at cmake_install.cmake:41 (file):
   file INSTALL cannot find "/root/emp-agmpc/cmake".
```
All you need to do is remove
the line
```
install(DIRECTORY cmake/ DESTINATION cmake)
```
from the `CMakeLists.txt` file

**Comment by wangxiao1254** [comment]
Will add a cmake config file

**Comment by wangxiao1254** [comment]
should be resolved.
