### ISSUE TITLE
threshold AG-MPC?

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-agmpc#5]
AG-MPC is full-threshold, meaning that one honest party is sufficient for security. 

In some settings, one may desire threshold security in exchange for better performance, e.g., assuming 20 out of 100 parties are honest, while the rest are malicious.

For arithmetic settings, SCALE-MAMBA provides such a threshold option, using Shamir secret sharing. 

But for Boolean circuit settings, a very flexible threshold setting seems missing. However, circuit representations matter, such as AES is commonly expressed in Boolean circuits.

Are any ongoing projects over emp-toolkit aimed for such a threshold setting? Any recommended readings over the malicious + threshold setting for Boolean circuits?

Thanks!

**Comment by wangxiao1254** [comment]
There is no support like that right now. There are some works for honest
majority like a multi-party garbling paper in CCS 2017. Another option is
to do committee selection to reduce the number of parties to a smaller
subset.

**Comment by weikengchen** [comment]
Thanks!
