### ISSUE TITLE
double_block -> sigma?

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-agmpc#8]
It seems that emp-toolkit is replacing `double_block` with `sigma`.

The `double_block` is removed from `emp-tool` in this commit https://github.com/emp-toolkit/emp-tool/commit/d707eacd02c0579926039c6a1757cddd688a78bd

However, `emp-agmpc` still uses `double_block`, as in here: https://github.com/emp-toolkit/emp-agmpc/blob/master/emp-agmpc/mpc.h#L443

Are we going to see a new version of `emp-agmpc` recently, which would use `sigma`?

**Comment by wangxiao1254** [comment]
I just put a hotfix. There will be a new implementation soon.
